### ISSUE TITLE
Not work Mac Os 10.14.2 vscode 1.31.0

### ISSUE THREAD

**Issue by prostodeb** [agurodriguez/vscode-enable-proposed-api#1]
hello 
You extension not work Mac Os 10.14.2 vscode 1.31.0.
error: ENOENT: no such file or directory, open 'undefined/package.json'

**Comment by agurod42** [comment]
Hi @prostodeb.

You're receiving this error because you're trying to use the extension without a project. The extension is intended to be used with a project that requires the Proposed API. I added a few error messages to express a little bit better this extension.
